pose_model: HRNet-W48
model_additional_weight: true
comment: null
result_dir: /home/ubuntu/fitness_django/inf_src/pushup/psu_models/keypoint/results
data_dir: /home/ubuntu/fitness_django/inf_src/pushup/psu_models/keypoint/data
debug: false
seed: 20210309

train:
  max_epochs: 200
  SAM: false
  folds: 
    - 1
    # - 2
    # - 3
    # - 4
    # - 5
  checkpoints: 
    - null
    - null
    - null
    - null
    - null
  loss_type: ce # ce, bce, mse, mae, awing, sigmae, kldiv
  
  finetune:
    do: true
    step1_epochs: 3
    step2_epochs: 6
    
  plus_augment:
    do: true
    downsample:
      do: true
      p: 0.2
      width: 256
      height: 256
    rotate:
      do: true
      p: 0.4
      left: true
      right: true
  
  # lr: 0.000001
  lr: 0.0001
  scheduler:
    # type: CosineAnnealingWarmUpRestarts
    # params:
    #   first_cycle_steps: 10
    #   cycle_mult: 1.0
    #   max_lr: 0.0001
    #   min_lr: 0.000001
    #   warmup_steps: 9
    #   gamma: 0.5
    # type: CosineAnnealingWarmRestarts
    # params:
    #   T_0: 10
    #   T_mult: 1
    #   eta_min: 0.00001
    #   verbose: false
    type: ReduceLROnPlateau
    params:
      factor: 0.5
      patience: 3
      verbose: true
  
dataset:
  train_dir: /home/ubuntu/fitness_django/inf_src/pushup/psu_models/keypoint/data/imgs
  target_file: /home/ubuntu/fitness_django/inf_src/pushup/psu_models/keypoint/data/train_df.csv
  test_dir: /home/ubuntu/fitness_django/inf_src/pushup/psu_models/keypoint/results
  
  scale_invariance: false
  normalize: true
  mean: [0.411, 0.420, 0.416]
  std: [0.307, 0.303, 0.292]
  smooth_heatmap: 
    do: true
    size: 3
    values: [0.1, 0.2, 0.5]
  input_width: 512
  input_height: 512
  ratio_limit: 2.0
  
  batch_size: 8 # 15 -> 8 ; cuz of OoM
  num_cpus: 4
  padding: 20
  
  group_kfold: false
  
test:
  tta:
    input_sizes: 
      # - [288, 384]
      - [576, 768]
      # - [864, 1152]
    rotations: 
      - 0
      # - 1
      # - 3
    horizontal_flip:
      # - false
      - true
    voting_method: key-median # mean, median, key-mean, key-median
